import { createFileRoute } from '@tanstack/react-router'
import { useCallback, useState } from 'react'
import { BoundaryMap, type Level, type Scenario } from '../components/BoundaryMap'
export const Route=createFileRoute('/')({component:Home})
const scenarios:Scenario[]=['current','a','b'],names={current:'Status quo',a:'Scenario A',b:'Scenario B'}
function Home(){
 const [level,setLevel]=useState<Level>('high'),[visible,setVisible]=useState<Scenario[]>(['a']),[address,setAddress]=useState(''),[position,setPosition]=useState<[number,number]|null>(null),[result,setResult]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const receive=useCallback((text:string)=>setResult(text),[])
 async function search(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const url=new URL('https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/findAddressCandidates');url.search=new URLSearchParams({f:'json',SingleLine:address,searchExtent:'-122.95,45.4,-122.45,45.75',outSR:'4326',maxLocations:'1',outFields:'Match_addr',forStorage:'false'}).toString();const r=await fetch(url,{signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error();const data=await r.json();const hit=data.candidates?.[0];if(!hit||hit.score<90)throw Error();const {x,y}=hit.location;if(x< -122.95||x> -122.45||y<45.4||y>45.75)throw Error();setPosition([y,x]);setResult(`Located ${hit.address}. Checking visible boundaries…`)}catch{setError('Could not confidently locate that address. Include Portland, OR, or click a neighborhood preset.')}finally{setBusy(false)}}
 return <><header><div><span className="eyebrow">PORTLAND PUBLIC SCHOOLS · OCTOBER 2026</span><h1>Where would we go?</h1><p>Explore attendance boundaries across status quo and the two proposals.</p></div><a href="https://meetings.boardbook.org/Public/Agenda/915?meeting=769955">PPS documents ↗</a></header><main><aside><form onSubmit={search}><label htmlFor="address">Find your address</label><div className="search"><input id="address" value={address} onChange={e=>setAddress(e.target.value)} placeholder="Street address, Portland, OR" required maxLength={240}/><button disabled={busy}>{busy?'Finding…':'Find'}</button></div><small>Your search is sent to Esri to locate the address. This app does not save it.</small></form>{error&&<p role="alert" className="error">{error}</p>}<label htmlFor="level">School level</label><select id="level" value={level} onChange={e=>setLevel(e.target.value as Level)}><option value="elementary">Elementary · K–5</option><option value="middle">Middle school · 6–8</option><option value="high">High school · 9–12</option></select><fieldset><legend>Show boundaries</legend>{scenarios.map(s=><label className="choice" key={s}><input type="checkbox" checked={visible.includes(s)} onChange={()=>setVisible(v=>v.includes(s)?v.filter(x=>x!==s):[...v,s])}/>{names[s]}</label>)}</fieldset><button className="preset" onClick={()=>setPosition([45.548,-122.603])}>Rose City Park area</button><section className="result" aria-live="polite"><h2>Your comparison</h2><p>{result||'Find an address to place it on the map and compare the boundary layers.'}</p><p className="notice">Boundary reconstruction preview. School names and assignments are awaiting verification; no school placement is asserted.</p></section><details><summary>Map sources & original PDFs</summary><p>The outlines are extracted from PPS’s vector PDFs and placed using the PDF geographic reference. Shapes still need topology, school-name and alignment review, including inset coverage.</p>{scenarios.map(s=><a className="source" key={s} href={`/maps/${s}-${level}.pdf`}>{names[s]} · original PDF ↗</a>)}<a className="source" href="/original/index.html">Open the original PDF comparison viewer ↗</a></details></aside><BoundaryMap level={level} scenarios={visible} position={position} onResult={receive}/></main></>
}
