import { createFileRoute } from '@tanstack/react-router'
import { useCallback, useEffect, useState } from 'react'
import type { FeatureCollection } from 'geojson'
import { BoundaryMap, type Level, type Scenario } from '../components/BoundaryMap'
import { assignmentsAt, levels, scenarios, type Assignment } from '../lib/assignments.mjs'
export const Route=createFileRoute('/')({component:Home})
const names={current:'Status quo',a:'Scenario A',b:'Scenario B'},levelNames={elementary:'Elementary',middle:'Middle',high:'High school'}
function SchoolResult({assignment}:{assignment:Assignment}){return <td className={assignment.status}>{assignment.schools.length?assignment.schools.map(name=><div key={name}>{name}</div>):'Not resolved'}{assignment.status==='ambiguous'&&<small>Multiple schools — check source map</small>}{assignment.unresolvedShapes? <small>Includes an unresolved boundary</small>:null}</td>}
function Home(){
 const [level,setLevel]=useState<Level>('high'),[visible,setVisible]=useState<Scenario>('a'),[address,setAddress]=useState(''),[position,setPosition]=useState<[number,number]|null>(null),[locationName,setLocationName]=useState(''),[focusSelection,setFocusSelection]=useState(false),[datasets,setDatasets]=useState<Record<string,FeatureCollection>|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[dataError,setDataError]=useState(false)
 useEffect(()=>{const controller=new AbortController();Promise.all(scenarios.flatMap(s=>levels.map(async l=>{const id=`${s}-${l}`,response=await fetch(`/data/${id}.geojson`,{signal:controller.signal});if(!response.ok)throw Error();return[id,await response.json()] as const}))).then(entries=>setDatasets(Object.fromEntries(entries))).catch(e=>{if(e.name!=='AbortError')setDataError(true)});return()=>controller.abort()},[])
 const select=useCallback((point:[number,number])=>{setPosition(point);setLocationName('Selected location');setFocusSelection(false);setError('')},[])
 const results=position&&datasets?assignmentsAt(datasets,[position[1],position[0]]):null
 async function search(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const url=new URL('https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/findAddressCandidates');url.search=new URLSearchParams({f:'json',SingleLine:address,searchExtent:'-122.95,45.4,-122.45,45.75',outSR:'4326',maxLocations:'1',outFields:'Match_addr',forStorage:'false'}).toString();const r=await fetch(url,{signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error();const data=await r.json();const hit=data.candidates?.[0];if(!hit||hit.score<90)throw Error();const {x,y}=hit.location;if(x< -122.95||x> -122.45||y<45.4||y>45.75)throw Error();setPosition([y,x]);setLocationName(hit.address);setFocusSelection(true)}catch{setError('Could not confidently locate that address. Include Portland, OR, or select a location on the map.')}finally{setBusy(false)}}
 return <><header><div><span className="eyebrow">PORTLAND PUBLIC SCHOOLS · OCTOBER 2026</span><h1>Compare your school pathways</h1><p>Choose a location to explore elementary, middle and high school in each scenario.</p></div><a href="https://meetings.boardbook.org/Public/Agenda/915?meeting=769955">PPS documents ↗</a></header><main><aside><form onSubmit={search}><label htmlFor="address">Find an address</label><div className="search"><input id="address" value={address} onChange={e=>setAddress(e.target.value)} placeholder="Street address, Portland, OR" required maxLength={240}/><button disabled={busy}>{busy?'Finding…':'Find'}</button></div><small>Your search is sent to Esri to locate the address. This app does not save it.</small></form>{error&&<p role="alert" className="error">{error}</p>}<label htmlFor="level">Boundary layer</label><select id="level" value={level} onChange={e=>setLevel(e.target.value as Level)}><option value="elementary">Elementary · K–5</option><option value="middle">Middle school · 6–8</option><option value="high">High school · 9–12</option></select><fieldset><legend>Map scenario</legend><div className="scenario-picker">{scenarios.map(s=><label className="choice" key={s}><input type="radio" name="scenario" value={s} checked={visible===s} onChange={()=>setVisible(s)}/>{names[s]}</label>)}</div></fieldset><section className="result" aria-live="polite"><h2>School pathways</h2>{dataError?<p role="alert">School data could not load. Please reload the page.</p>:!position?<p>Click anywhere on the map or search an address to compare all three scenarios.</p>:!results?<p>Loading school pathways…</p>:<><p className="location-name">{locationName}</p>{scenarios.map(s=><div className="pathway" key={s}><h3>{names[s]}</h3><table aria-label={`${names[s]} school pathway`}><tbody>{levels.map(l=><tr key={l}><th scope="row">{levelNames[l]}</th><SchoolResult assignment={results[s][l]}/></tr>)}</tbody></table></div>)}</>}<p className="notice">Estimated neighborhood assignments from PPS proposal maps. Unresolved or overlapping boundaries are shown explicitly. Lottery and immersion placements may differ.</p></section><details><summary>Map sources & original PDFs</summary><p>School names are matched to the labels inside the original PDF boundaries. The map reconstruction is approximate, and northwest inset coverage remains incomplete.</p>{scenarios.map(s=><a className="source" key={s} href={`/maps/${s}-${level}.pdf`}>{names[s]} · original PDF ↗</a>)}<a className="source" href="/original/index.html">Open the original PDF comparison viewer ↗</a></details></aside><BoundaryMap level={level} scenario={visible} position={position} focusSelection={focusSelection} onSelect={select}/></main></>
}
