import { useEffect, useRef, useState } from 'react'
import type { Map as LeafletMap, LayerGroup } from 'leaflet'
import type { FeatureCollection } from 'geojson'
export type Level = 'elementary'|'middle'|'high'
export type Scenario = 'current'|'a'|'b'
const names={current:'Status quo',a:'Scenario A',b:'Scenario B'}
const colors={current:'#52667e',a:'#e16935',b:'#008b7e'}
type Props={level:Level;scenario:Scenario;position:[number,number]|null;focusSelection:boolean;onSelect:(point:[number,number])=>void}
export function BoundaryMap({level,scenario,position,focusSelection,onSelect}:Props){
 const container=useRef<HTMLDivElement>(null),map=useRef<LeafletMap|null>(null),group=useRef<LayerGroup|null>(null),markerGroup=useRef<LayerGroup|null>(null)
 const select=useRef(onSelect);select.current=onSelect
 const [ready,setReady]=useState(false),[error,setError]=useState('')
 useEffect(()=>{let disposed=false;import('leaflet').then(L=>{if(disposed||!container.current)return;map.current=L.map(container.current).fitBounds([[45.42,-122.83],[45.65,-122.54]]);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,updateWhenIdle:true,keepBuffer:1,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).on('tileerror',()=>setError('Street tiles could not load. Boundary outlines remain available.')).addTo(map.current);group.current=L.layerGroup().addTo(map.current);markerGroup.current=L.layerGroup().addTo(map.current);map.current.on('click',e=>select.current([e.latlng.lat,e.latlng.lng]));setReady(true)}).catch(()=>setError('Could not initialize the map.'));return()=>{disposed=true;map.current?.remove();map.current=null}},[])
 useEffect(()=>{if(!ready)return;const controller=new AbortController();Promise.all([scenario].map(async scenario=>{const r=await fetch(`/data/${scenario}-${level}.geojson`,{signal:controller.signal});if(!r.ok)throw Error();return{scenario,data:await r.json() as FeatureCollection}})).then(async data=>{const L=await import('leaflet');if(controller.signal.aborted||!group.current)return;group.current.clearLayers();for(const {scenario,data:fc}of data){L.geoJSON(fc,{style:()=>({color:colors[scenario],weight:2,fillOpacity:.1,dashArray:scenario==='current'?'6 4':undefined}),onEachFeature:(feature,layer)=>{const content=document.createElement('span');content.textContent=`${names[scenario]} · ${feature.properties?.school_name??'School boundary'}`;layer.bindTooltip(content)}}).addTo(group.current)}}).catch(e=>{if(e.name!=='AbortError')setError('Boundary data could not load. Try reloading.')});return()=>controller.abort()},[ready,level,scenario])
 useEffect(()=>{if(!ready||!position)return;let cancelled=false;import('leaflet').then(L=>{if(cancelled||!markerGroup.current)return;markerGroup.current.clearLayers();L.circleMarker(position,{radius:7,color:'#152e42',fillColor:'white',fillOpacity:1,weight:3}).addTo(markerGroup.current);if(focusSelection)map.current?.setView(position,15)});return()=>{cancelled=true}},[ready,position,focusSelection])
 return <div className="map-wrap"><div ref={container} className="map" aria-label="Click the map to compare elementary, middle and high school assignments"/>{error&&<p className="map-error" role="alert">{error}</p>}<div className="map-key">{[scenario].map(s=><span key={s}><i style={{background:colors[s]}}/>{names[s]}</span>)}</div><div className="click-tip">Click anywhere to compare school pathways</div></div>
}
