import { useEffect, useRef, useState } from 'react'
import type { Map as LeafletMap, LayerGroup } from 'leaflet'
import type { FeatureCollection } from 'geojson'
import { lookup } from '../lib/geometry.mjs'
export type Level = 'elementary'|'middle'|'high'
export type Scenario = 'current'|'a'|'b'
const names={current:'Status quo',a:'Scenario A',b:'Scenario B'}
const colors={current:'#52667e',a:'#e16935',b:'#008b7e'}
type Props={level:Level;scenarios:Scenario[];position:[number,number]|null;onResult:(message:string)=>void}
export function BoundaryMap({level,scenarios,position,onResult}:Props){
 const container=useRef<HTMLDivElement>(null),map=useRef<LeafletMap|null>(null),group=useRef<LayerGroup|null>(null)
 const [ready,setReady]=useState(false),[error,setError]=useState('')
 useEffect(()=>{let disposed=false;import('leaflet').then(L=>{if(disposed||!container.current)return;map.current=L.map(container.current).setView([45.54,-122.65],12);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,updateWhenIdle:true,keepBuffer:1,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).on('tileerror',()=>setError('Street tiles could not load. Boundary outlines remain available. Check your connection or tile-service access.')).addTo(map.current);group.current=L.layerGroup().addTo(map.current);setReady(true)}).catch(()=>setError('Could not initialize the map.'));return()=>{disposed=true;map.current?.remove();map.current=null}},[])
 useEffect(()=>{if(!ready)return;const controller=new AbortController();setError('');Promise.all(scenarios.map(async scenario=>{const r=await fetch(`/data/${scenario}-${level}.geojson`,{signal:controller.signal});if(!r.ok)throw Error('Map data unavailable');return{scenario,data:await r.json() as FeatureCollection}})).then(async data=>{const L=await import('leaflet');if(controller.signal.aborted||!group.current)return;group.current.clearLayers();for(const {scenario,data:fc}of data){L.geoJSON(fc,{style:()=>({color:colors[scenario],weight:2,fillOpacity:scenarios.length===1?.1:.025,dashArray:scenario==='current'?'6 4':undefined}),onEachFeature:(feature,layer)=>{const content=document.createElement('div');content.textContent=`${names[scenario]} · ${feature.properties?.school_name??feature.properties?.boundary_id} · extracted boundary, awaiting review`;layer.bindPopup(content)}}).addTo(group.current)}if(position){L.circleMarker(position,{radius:7,color:'#152e42',fillColor:'white',fillOpacity:1,weight:3}).addTo(group.current);map.current?.setView(position,15);const matches=data.map(({scenario,data:fc})=>`${names[scenario]}: ${lookup(fc,[position[1],position[0]]).length} provisional shape(s) at this location`);onResult(matches.join(' · ')+'. School assignment is pending boundary review.')}}).catch(e=>{if(e.name!=='AbortError')setError('Boundary data could not load. Try reloading.')});return()=>controller.abort()},[ready,level,scenarios,position,onResult])
 return <div className="map-wrap"><div ref={container} className="map" aria-label="PPS attendance boundaries street map"/>{error&&<p className="map-error" role="alert">{error}</p>}<div className="map-key">{scenarios.map(s=><span key={s}><i style={{background:colors[s]}}/>{names[s]}</span>)}</div></div>
}
